// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpjupbtxnuuwbovztlrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwanVwYnR4bnV1d2Jvdnp0bHJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNTQ4NjksImV4cCI6MjA2NTkzMDg2OX0.iRK-HikDXgTtGxP_I-6ECykjNilRCqRWLQN4PJxFKNY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);